-- Create table in h2
CREATE TABLE IF NOT EXISTS INBOUND_BATCH (ID BIGINT AUTO_INCREMENT PRIMARY KEY, BATCH_TYPE VARCHAR(10), IDENTIFICATION VARCHAR(255), CREATED TIMESTAMP, ACKNOWLEDGE TIMESTAMP);
CREATE TABLE IF NOT EXISTS OUTBOUND_BATCH (ID BIGINT AUTO_INCREMENT PRIMARY KEY, BATCH_TYPE VARCHAR(10), IDENTIFICATION VARCHAR(255), CREATED TIMESTAMP, ACKNOWLEDGE TIMESTAMP);
CREATE TABLE IF NOT EXISTS ELHUB_MESSAGE (ID BIGINT AUTO_INCREMENT PRIMARY KEY, INBOUND_BATCH_ID BIGINT, IDENTIFICATION VARCHAR(255), JURIDICAL_RECIPIENT VARCHAR(255), MESSAGETYPE VARCHAR(255), ENDPOINTTYPE VARCHAR(255), OUTBOUND_BATCH_ID BIGINT, MESSAGE VARCHAR(32000)); 
