-- Create table in postgresql
CREATE TABLE INBOUND_BATCH (ID BIGSERIAL PRIMARY KEY, IDENTIFICATION VARCHAR(255), CREATED TIMESTAMP, ACKNOWLEDGE TIMESTAMP);
CREATE TABLE OUTBOUND_BATCH (ID BIGSERIAL PRIMARY KEY, IDENTIFICATION VARCHAR(255), CREATED TIMESTAMP, ACKNOWLEDGE TIMESTAMP);
CREATE TABLE ELHUB_MESSAGE (ID BIGSERIAL PRIMARY KEY, INBOUND_BATCH_ID BIGINT REFERENCES INBOUND_BATCH (ID), IDENTIFICATION VARCHAR(255), JURIDICAL_RECIPIENT VARCHAR(255), MESSAGETYPE VARCHAR(255), ENDPOINTTYPE VARCHAR(255), OUTBOUND_BATCH_ID BIGINT REFERENCES OUTBOUND_BATCH (ID), MESSAGE TEXT); 